#!/usr/bin/env bash

# download git prompt script
curl -o "$HOME/scripts/git-prompt.sh" -L https://raw.githubusercontent.com/git/git/refs/heads/master/contrib/completion/git-prompt.sh

# download git bash completion script
curl -o "$HOME/scripts/git-completion.bash" -L https://raw.githubusercontent.com/git/git/refs/heads/master/contrib/completion/git-completion.bash

source "$HOME/.bashrc"

